### ISSUE TITLE
[Trawlwatch] ValueError: cannot convert float NaN to integer whrn reaching max vayage_id

### ISSUE THREAD

**Issue by rv2931** [dataforgoodfr/12_bloom#100]
When we display trajectory of a vessel, when voyage_id reach the max limit (voyage_id=2) an error is thrown

`bloom           | 2024-03-08 11:34:06.925 Uncaught app exception
bloom           | Traceback (most recent call last):
bloom           |   File "/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
bloom           |     exec(code, module.__dict__)
bloom           |   File "/project/src/pages/1_Vessel_Exploration.py", line 110, in <module>
bloom           |     change_range(voyage_id)
bloom           |   File "/project/src/pages/1_Vessel_Exploration.py", line 99, in change_range
bloom           |     min_value = int(vf.index.min())
bloom           | ValueError: cannot convert float NaN to integer`

This erreor seems to be added by PR https://github.com/dataforgoodfr/12_bloom/pull/87

Cf : https://github.com/dataforgoodfr/12_bloom/pull/98 for discussion about this

![image](https://github.com/dataforgoodfr/12_bloom/assets/14039054/a1035884-1f38-4e2f-be2a-884851c51ba9)

![image](https://github.com/dataforgoodfr/12_bloom/assets/14039054/7cf93a4e-53f0-4622-b90d-2de0113b99e9)

**Comment by njouanin** [comment]
Obsolète
