### ISSUE TITLE
set up a cache mechanism to save source extractions (Spire API and others) for reuse in test/dev

### ISSUE THREAD

**Issue by rv2931** [dataforgoodfr/12_bloom#110]
The idea is to set up a mecanism that could store API responses in production in file or BDD (sqlite ?) and the application could reuse these informations to rebuild source data for test/dev environment

The cache mecanism should be explicitly activated/deactivated by configuration for stroring and/or reuse phase

**Comment by njouanin** [comment]
Tu peux m'assigner cette tâche ?

**Comment by njouanin** [comment]
TAF:
* Enregistrement dans un fichier JSON de la liste des réponses spire dans un répertoire passé en paramètre du traitement
* Développement d'un script permettant d'injecter un fichier en entrée du traitement d'intégration spire
