### ISSUE TITLE
Simplifier l'intégration des ports pour n'importer que des données brutes, sans données intermédiaires

### ISSUE THREAD

**Issue by rv2931** [dataforgoodfr/12_bloom#114]
Actuellement il y a un fichier ports.csv qui contient les coordonnées géographiques des ports puis un ports_rad3000_res10.csv issu d'un process de transformation de ports.csv mais contenant des zones correspondantes au port plutôt que simplement leur coordonnées

Dans l'idée il faudrait que dans DATA ont aient besoin que du fichier ports.csv de données initiales, à renomme ports_subsets, je dirais même harbours_subsets.csv si on maintien l'anglais contenant les coordonnées
Pour la génération des zones c'est quelque chose qui, si des zones doivent être générées, sont des process qui devraient être inclus dans le process d'import des harbours_subsets.csv sans fichier intermédiaire
@romainm13 @njouanin

**Comment by njouanin** [comment]
Suite PR #123 seul 1 fichier csv est nécessaire.
