### ISSUE TITLE
Revoir la mapping SQLAchemy ou étudier une migration vers SQLModel

### ISSUE THREAD

**Issue by njouanin** [dataforgoodfr/12_bloom#128]
Le code actuel utilise la syntaxe impérative de SQLAlchemy.
Depuis SQLAlchemy 2, la [syntaxe déclarative](https://docs.sqlalchemy.org/en/20/orm/mapping_styles.html#orm-mapping-styles) est préconisée => modifier le mapping (`src/bloom/infra/database/sql_model.py`) pour utiliser cette syntaxe.

OU: étudier la migration vers [SQLModel](https://sqlmodel.tiangolo.com/), qui permet de fusionner le mapping Pydantic avec le mapping SQLAlchemy.

**Comment by njouanin** [comment]
note: SQLModel ne parait pas très stable pour l'instant.

**Comment by rv2931** [comment]
> note: SQLModel ne parait pas très stable pour l'instant.

Ok... Bin c'était une idée mais pour avoir mis le nez dans la partie infra database je vois complètement l'intérêt de ce SqlModel parce qu'en l'état c'est bien lourd je touvrpour avoir et les avantages de Pydantic et l'ORM alchemy... Mais soit si tu penses que c'est pas une bonne idée en l'état faut abandonner l'idée. Toutes façon très clairement on aura pas le temps là

**Comment by njouanin** [comment]
C'est une remarque qu'avait fait quelqu'un sur Slack.

**Comment by rv2931** [comment]
J'ai regardé un peu. FastAPI est quand même une référence aujourd'hui à priori et le lien avec SQLModel qui est maintenu par la même équipe semble assez courant
La migration semble assez facile à priori
https://www.youtube.com/watch?v=pRYzMF04fLw
