### ISSUE TITLE
Compatibilité python 3.8 -> 3.10

### ISSUE THREAD

**Issue by hehlinge42** [dataforgoodfr/12_bloom#132]
Le fichier src/bloom/domain/spire_ais_data.py importe "Self" from typing. Hors, cet objet a été ajouté dans python3.11 et n'est donc pas compatible avec les versions précédentes de Python. L'image Docker du projet héritant de python3.10, elle n'est donc pas compatible avec cet import.

Traceback (most recent call last):
  File “/project/src/bloom/tasks/compute_port_geometry_buffer.py”, line 8, in <module>
    from bloom.container import UseCases
  File “/project/src/bloom/container.py”, line 6, in <module>
    from bloom.infra.repositories.repository_spire_ais_data import SpireAisDataRepository
  File “/project/src/bloom/infra/repositories/repository_spire_ais_data.py”, line 1, in <module>
    from bloom.domain.spire_ais_data import SpireAisData
  File “/project/src/bloom/domain/spire_ais_data.py”, line 2, in <module>
    from typing import Any, Self
ImportError: cannot import name ‘Self’ from ‘typing’ (/usr/local/lib/python3.10/typing.py)

Solution proposée : 
Comme proposé dans https://stackoverflow.com/questions/77247446/cannot-import-name-self-from-typing , l'import 
```
from typing import Self
```

peut être remplacé par 
```
from typing_extensions import Self
```

**Comment by rv2931** [comment]
Bien vu 
Pour 3.8 malheureusement il y a une contrainte sur un autre paquet, geopandas utilisé mais si on peut garder 3.9, 3.10 et 3.11 c'est mieux. 3.12 là aussi il y a un paquet (dependency_injection) qui n'est pas compatible. Par contre je n'ai pas fait le check de savoir si ce dernier paquet était vraiment nécessaire ou non

**Comment by njouanin** [comment]
oui, ou plus simple on enlève l'annotation du type de retour de la fonction.
