### ISSUE TITLE
Prise en compte de la date d'exécution des traitements

### ISSUE THREAD

**Issue by njouanin** [dataforgoodfr/12_bloom#135]
On a des traitements de mise à jour de la base de données qui vont s'enchainer à intervalles réguliers.
A chaque exécution, il est préférable qu'un traitement ne traite que les données créées ou modifiées depuis sa dernière exécution.
Pour cela, on a dans chaque table un champ `created_at` (et éventuellement un champ `updated_at`) qui indique la date de création/modification de chaque enregistrement => ces champs peuvent faire partie des critères de sélection lorsqu'un traitement recherche les données qu'il doit traiter.
En complément, il faut donc stocker, pour chaque traitement, sa date de dernière exécution. 
 - cette date serait mise à jour à la fin du traitement, si le traitement se termine avec succès
 - et relue à l'exécution suivante pour rechercher les nouvelles données

Proposition: créer une table qui stocke, pour chaque traitement, sa date de dernière exécution.

**Comment by rv2931** [comment]
Je connais ce genre de mécanisme, genre une table qui stocke la date de dernière exécution basé sur le nom du fichier du script, ce qui permet de rendre le truc automatique même avec renommage du script
Par contre le souci que je vous c'est qu'il n'y a pas de borne de fin pour faire du traitement par lot délimité dans le temps et garder une certaine equivalence
Dans le détail si on veut traiter 1 mois de données ça va faire un beaucoup de données d'un coup en mettant la  date last_execution à J-30j
Perso je préfère le mode airflow de traitement par lot ou on créerait 30x24x4 requêtes sur des tranches de 15 minutes bornées. D'ailleurs je ne suis pas certain que l'API spire accepte des requêtes de données sur des grandes périodes. => A vérifier

**Comment by rv2931** [comment]
Au pire ça peut être un découpage fait au sein de la tâche
start=last_execution end=now
While t<end : requêtes sur (end-start)/15min+offset_start
Algos cité fait mais ça pourrait être l'idee

**Comment by rv2931** [comment]
Sachant que pour tout ce qui est acquisition API c'est pas mal de prévoir 2/3 retry espacé dans le temps de 20/30 secondes en cas de problème réseau passager

**Comment by njouanin** [comment]
En nominal on a environ 1800 positions toutes les 15 minutes. Il faudrait benchmarker mais ça reste limité en volume. Le pb se pose effectivement si on veut traiter de gros volumes, par exemple recalculer des anciens trucs avec de nouveaux algo.
Dans ce cas, oui on pourrait lotir.

**Comment by njouanin** [comment]
Fait.
