### ISSUE TITLE
Gestion des mises à jour de la table dim_vessel

### ISSUE THREAD

**Issue by njouanin** [dataforgoodfr/12_bloom#140]
## Besoin
Le traitement `LoadDimVesselFromCsv` ne gère actuellement que le chargement (INSERT) des données depuis un fichier CSV. Les mises à jour et suppression ne sont pas gérées. De plus il est souhaité la possibilité de désactiver un bateau afin de ne plus suivre ses informations (bateau sans intérêts, démantelé, ...).
Les changements suivants sont nécessaires:
 - suppression de la colonne `mt_activated` de la table `dim_vessel`
 - suppression de la contrainte d'unicité sur `dim_vessel.mmsi`
 - création de 2 nouvelles colonnes:
    - `tracking_activated` booléen
    -  `tracking_status` varchar

La colonne `tracking_activated` est utilisée lors des appels à l'API SPIRE. Seuls le MMSI des bateaux ayant une valeur `tracking_activated==TRUE` sont interrogés pour faire l'objet d'un suivi AIS.
La colonne `tracking_status` permet à l'utilisateur de préciser dans un format libre la raison de la désactivation.

## Gestion des changements lors des chargements d'un nouveau fichier CSV
Pour chaque enregistrement du fichier:
 - si la valeur du champ `id` n'est pas vide:
   - rechercher l'enregistrement correspondant dans la table `dim_vessel`
   - mettre à jour l'enregistrement à partir des données CSV.
 - sinon:
   - insérer les données CSV dans la table `dim_vessel`;

En fin de traitement:
 - les enregistrements de la table `dim_vessel` pourtant un MMSI absent du fichier CSV sont mis à jour avec la valeur `tracking_activated=FALSE`
 - le traitement vérifie qu'il n'existe qu'un seul enregistrement à l'état `tracking_activated==True` pour chaque valeur distincte de MMSI.

Format attendu pour le fichier CSV, identique aux colonnes de la table `dim_vessel`:
`id;mmsi;ship_name;width;length;country_iso3;type;imo;cfr;registration_number;external_marking;ircs;tracking_activated;tracking_status`

## Utilisation
 - Exporter le contenu de la table `dim_vessel` en CSV.
 - apporter les modification nécessaires dans le fichier CSV de la manière suivante:
    - laisser inchangés les enregistrements à jour
    - mettre à jour les données des enregistrement existants (les champs `created_at` et `updated_at` peuvent être ignorés)
    - ajouter les nouveaux bateaux en respectant le format CSV. Important: laisser la colonne `vide.`
    - supprimer les lignes des bâteaux à désactiver ou positionner l'indicateur tracking_activated à False des enregistrements concernés.
  - vérifier qu'il n'existe qu'un seul enregistrement à l'état `tracking_activated==True` pour chaque valeur distincte de MMSI sinon le traitement échouera
  - placer le fichier en entrée du traitement et lancer l'intégration.

**Comment by rv2931** [comment]
je me questionne que le fait que les bateaux non présent CSV soient forcément mis à TRUE
Je pense que c'est au niveau de l'appli qui décidera de mettre un vessel en tracking ou non, du coup vaudrait pas mieux laisser la valeur tracking telle qu'elle est quand le bateau est absent du CSV ?
