### ISSUE TITLE
Nettoyage / mise à jour du fichier de référence des chalutiers

### ISSUE THREAD

**Issue by njouanin** [dataforgoodfr/12_bloom#147]
Le fichier de référence des chalutiers suivis par Trawlwatch nécessite d'être nettoyé et adapté au format de la nouvelle base de données.
Ci-joint le fichier de référence actuel convertit dans le nouveau format. Est-il possible de le nettoyer (suppression des MMSI=None) et de le compléter en fonction des besoins.

Voir l'issue #140 pour la description des éléments attendus.

**Comment by njouanin** [comment]
[chalutiers_pelagiques.csv](https://github.com/dataforgoodfr/12_bloom/files/14813349/chalutiers_pelagiques.csv)

**Comment by marthevienne** [comment]
Table nettoyé et mise à jour [ici](https://subset-s12-trawlwatch.s3.fr-par.scw.cloud/updated_vessels_table.csv)

**Comment by njouanin** [comment]
OK, je prends en compte.
Est-ce que tu confirmes également la suppression de la colonne `registration_number` (cf.  #148)

**Comment by marthevienne** [comment]
Je confirme

**Comment by njouanin** [comment]
Fichier chargé et colonnes ajoutées.
