### ISSUE TITLE
Suppression de dim_vessel.registration_number

### ISSUE THREAD

**Issue by njouanin** [dataforgoodfr/12_bloom#148]
Suite commentaire de Marthe sur miro, supprimer la colonne `registration_number` de la table `dim_vessel`:
 - script alembic
 - mise à jour des couches ORM et domain
 - impact sur les traitements.

**Comment by sarahlunette** [comment]
Mise à jour de vessel.py, repository_vessel_data.py, create_vessel_data.py, load_dim_vessel_from_csv.py, sql_model.py

**Comment by njouanin** [comment]
Corrigé avec #161
