### ISSUE TITLE
Ajout d'une colonne commentaire dans dim_vessel

### ISSUE THREAD

**Issue by njouanin** [dataforgoodfr/12_bloom#152]
Marthe souhaite disposer d'une zone de commentaire libre associé à chaque bateau.
- ajouter une colonne `comment`, de type `String` dans la table `dim_vessel` (création d'une révision alembic)
- modification du modèle SQL
- modification de la couche domaine
- impact sur la couche repository

Il faut également modifier le traitement `load_dim_vessel_from_csv.py` pour prendre en compte cette colonne dans les données importées depuis le fichier CSV (voir issue #140 et #147 sur le sujet)

**Comment by sarahlunette** [comment]
Ca fait modifier les fichiers suivants: sql_model.py, repository_vessel.py, /load_dim_vessel_from_csv.py. Y a-t'il autre chose ? (je ne sais pas ce que c'est la couche domain et comment on fait le premier si c'est pas dans le modèle SQL (à moins qu'on fasse une commande du type:
alembic revision --autogenerate -m
alembic upgrade head 
@njouanin

**Comment by njouanin** [comment]
Bonjour, j'ai ajouté une review sur la PR #161.
