### ISSUE TITLE
Streamlit not working

### ISSUE THREAD

**Issue by sarahlunette** [dataforgoodfr/12_bloom#162]
En déployant le streamlit je trouve ça:
```
“/project/src/bloom/infra/repositories/repository_vessel.py”, line 215, in get_vessel_trajectory
    metadata = {k: v for k, v in vessel.__dict__.items() if k != “_sa_instance_state”}
```
En essayant simplement en excluant les NoneType, ça ne fonctionne pas non plus
mais on va trouver une solution

**Comment by njouanin** [comment]
La partie streamlit est obsolète et doit être supprimée à terme. La fonction `get_vessel_trajectory` de repository_vessel utilise l'ancien modèle de données et est donc également obsolète.
