### ISSUE TITLE
test_vessel_is_in_port: Configurer une bdd pour les github actions (test fail)

### ISSUE THREAD

**Issue by rv2931** [dataforgoodfr/12_bloom#170]
Un test test_vessel_is_in_port a été rajouté dans le backend. Ce test attend un accès à une base de données initialisée avec la dim_port cependant cette base de données n'est pas montée/configurée/initialisée côte github actions
Les tests ont été désactivé dans tox le temps de rendre fonctionnel les tests

**Comment by njouanin** [comment]
Voir #143
