### ISSUE TITLE
[frontend] erreur au build en mode dev du frontend

### ISSUE THREAD

**Issue by rv2931** [dataforgoodfr/12_bloom#184]
Quand je lance le front dans un conteneur docker et que je charge le dashboard j'ai cette erreur
J'ai tenté un npm install map-store mais ça ne résout pas le problème
```
./components/providers/map-store-provider.tsx:6:0
Module not found: Can't resolve '@/lib/stores/map-store'
  4 | import { useStore, type StoreApi } from "zustand"
  5 | 
> 6 | import { createMapStore, type MapStore } from "@/lib/stores/map-store"
  7 | 
  8 | export const MapStoreContext = createContext<StoreApi<MapStore> | null>(null)
  9 | 

https://nextjs.org/docs/messages/module-not-found
```

**Comment by marthevienne** [comment]
essayer `npm install **--save** map-store` ?

**Comment by rv2931** [comment]
Je laisse les gens du front corriger, je vais me limiter à intégrer les update pour le moment concernant nextjs :)

**Comment by tanega** [comment]
Yo, @rv2931 @marthevienne un `npm install map-store` ne résoudra pas le pb, le `@/` est un alias d'import local, voir le `tsconfig.json`. Je vais vois si je peux pas fixer ça 🤞

**Comment by ValentinCalafell** [comment]
Salut, est ce qu'on a du nouveau sur cette issue ?
