### ISSUE TITLE
[Dashboard] - Date picker

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_bloom#214]
L'utilisateur peut filtrer par plage de temps la période de l'activité.

https://www.figma.com/design/MNnJ7bfa4tS7txveGikQOx/Bloom-Trawlwatch-(DEF)?node-id=338-2954&node-type=canvas&t=g01zV0ROgS5Wt85S-0

<img width="319" alt="image" src="https://github.com/user-attachments/assets/2e8c718c-b107-417a-8310-8a4802e5ed54">

variables à prendre : 
- 7 derniers jours / 
- 15 derniers jours 
- 1 mois
- 3 mois
- 1 an

**Comment by marthevienne** [comment]
ERRATUM: la plage de temps est incrémentable (+ 1 jour)
On ne l'a pas changé sur la maquette mais Hervé avait géré ça avec Côme.

**Comment by alexphiev** [comment]
Fait
