### ISSUE TITLE
Documentation de l'API

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_bloom#219]
Avoir accès à la documentation de l'API pour vérifier comment elle est construite et quelles variables sont disponibles

notamment répondre à cette question : pour la documentation du nom des variables est-ce que vous pouvez confirmer que tous les noms de champs restent les memes ?

@SebM42 pour suivi

**Comment by SebM42** [comment]
Doc de l'API ici : https://app-50bfd872-632e-4cb6-abc2-b94479db4d03.cleverapps.io/docs#/ 

(thx Amine)
