### ISSUE TITLE
FCT_Excursions - Colonne "total_time_extincting_amp" non calculée

### ISSUE THREAD

**Issue by SebM42** [dataforgoodfr/12_bloom#221]
Colonne _total_time_extincting_amp_ dans la tache _create_update_excursions_segments.py_ non calculée

Rappel du calcul : somme de _fct_segment.segment_duration_ appartenant à l'excursion et ayant _fct_segment.type_ égal à _DEFAULT_AIS_

**Comment by njouanin** [comment]
Corrigé. Par contre la correction ne porte que sur les excursions créées ou mises à jour depuis la correction (maintenant). Pour les excursions existantes, le recalcul serait trop compliqué à faire.
