### ISSUE TITLE
API - probleme d'accès sur la prod depuis l extérieur

### ISSUE THREAD

**Issue by SebM42** [dataforgoodfr/12_bloom#223]
EDIT !

Détail de la requete : 
GET
Headers : {'accept':'application/json','x-key':'bloom'}
url : https://app-50bfd872-632e-4cb6-abc2-b94479db4d03.cleverapps.io/api/v1/ports

Réponse : 'Internal Server Error'

**Comment by rv2931** [comment]
Tu le fait avec quel outil ? curl ? sur quel endpoint ?
Issu de la doc swagger ça donnerait ça : 
```
curl -X 'GET' \
  'https://XXXX.cleverapps.io/api/v1/cache/all/flush' \
  -H 'accept: application/json' \
  -H 'x-key: bloom'
```
 Avec ces paramètres j'arrive sur une erreur 500 (en prod) et non une erreur "Method not allowed", c'est assez bizarre
 Mais mon erreur est liée à l'absence de service Redis
 redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
 
 Donc pas de réponse à ce ticket pour le moment

**Comment by SebM42** [comment]
je le fais directement en python, j'ai oublié de préciser l'url : 'https://app-50bfd872-632e-4cb6-abc2-b94479db4d03.cleverapps.io/api/v1/ports'

**Comment by SebM42** [comment]
Issues transférée : https://github.com/dataforgoodfr/12_bloom/issues/229
