### ISSUE TITLE
[Data] Règles concernant les zones

### ISSUE THREAD

**Issue by marthevienne** [dataforgoodfr/12_bloom#224]
3 types de zone nous intéressent pour TrawlWatch.
1. les aires marines protégées (AMP) (`CATEGORY = amp`)
2. les eaux territoriales (0-12 NM) (`CATEGORY = Territorial seas`)
3. les bande côtières françaises de pêche  (`CATEGORY = Fishing coastal waters (6-12 NM)`)

Voici un résumé des règles qui y sont appliquées pour TrawlWatch :

### **1. LES AIRES MARINES PROTÉGÉES**
Il existe 32 `sub_category` d'AMP reflétant des juridictions différentes.

Des AMP d'une même `sub_category` ne se chevauchent pas. En revanche, des AMP de `sub_category` différentes peuvent se chevaucher (différents niveaux de juridiction). 

Exemple : dans le cas des AMP appelées Bancs des Flandres, la géométrie varie légèrement d'une `sub_category` à l'autre mais le chevauchement est quasiment intégral.
<img width="692" alt="Capture d’écran 2024-10-28 à 12 10 00 PM" src="https://github.com/user-attachments/assets/e98aac9c-2a9b-4aea-b24a-20ea324781be">
<img width="600" alt="Capture d’écran 2024-10-28 à 12 12 28 PM" src="https://github.com/user-attachments/assets/5acf14ce-19df-4be1-b2f2-bf54dde6609f">

**Règle** : la pêche n'y est pas interdite sauf dans 1-2 `sub_category` très peu répandues (Integral nature reserve et National Park - Integrale Reserve). Pour l'instant dans TrawlWatch, on fait l'hypothèse que la pêche est interdite dans aucune des `sub_category` d'AMP.

### **2. EAUX TERRITORIALES**
Les eaux territoriales sont la bande entre le trait de base à la côte et 12 NM au large. Ces eaux sont **strictement réservées à la pêche par les navires français** (dim_vessel: `country_iso3 = FRA`) **à l'exception** des bandes côtières de pêche qui sont des zones dans ces eaux territoriales régit par des accords avec des pays limitrophes. 

<img width="300" alt="Capture d’écran 2024-11-18 à 11 10 14 AM" src="https://github.com/user-attachments/assets/2da679ef-ca2b-4ae8-bd3e-c7ccebf30af9">
<img width="300" alt="Capture d’écran 2024-11-18 à 11 10 55 AM" src="https://github.com/user-attachments/assets/6e6064a2-1e52-4ea1-b787-3638dabd79b2">

**ATTENTION : la pêche y est interdite mais la présence d'un navire étranger dans ces eaux n'est pas illégale. Ils ont le droit de les traverser.**

### **3. BANDES CÔTIÈRES FRANÇAISES DE PÊCHE**
Les bandes côtières de pêche sont des sous-zones des eaux territoriales régies par des accords avec les pays limitrophes.
<img width="801" alt="Capture d’écran 2024-10-28 à 12 51 42 PM" src="https://github.com/user-attachments/assets/b6bf176b-4fda-4d85-9a3a-39187a9bdaad">

Les navires sous pavillon inclu dans les `beneficiaries` d'une bande côtière ont le droit d'y pêcher ainsi que les navires sous pavillon FRA. En revanche, les autres navires étrangers n'ont pas le droit d'y pêcher.
<img width="821" alt="Capture d’écran 2024-10-28 à 12 24 59 PM" src="https://github.com/user-attachments/assets/ea5b098b-0544-4b1d-b36a-e93ca5a9ad65">

### **4. RÈGLES DE CALCUL DES DURÉES**
Sachant qu'un navire peut à la fois être dans les eaux territoriales, dans une bande côtière de pêche et dans des AMP au même moment, comment gérer cela ?
<img width="1200" alt="Capture d’écran 2024-10-28 à 3 32 14 PM" src="https://github.com/user-attachments/assets/47e8ffca-acd9-40bb-b5a9-5175c87d104b">

- Traiter chaque zone séparément : on veut savoir le temps qu'un navire à passer dans **chaque** zone.
- Le temps passé dans les AMP n'est pas égal à la somme des temps dans chaque AMP. Il faut le calculer en faisant l'union de toutes les AMP.
- Le temps passé dans les bandes côtières de pêche ne nous intéresse pas en tant que tel. On s'intéresse plutôt à un ensemble de zone qu'on a appelé les **_zones with no fishing rights_**. Ces zones sont dépendantes du pavillon du navire. Pour les navires étrangers (hors FRA) : eaux territoriales - les bandes côtières où le pavillon du navire est inclu dans les bénéficiaires. Pour les navires français, il n'y a pas de _zones with no fishing rights_.
- Le temps passé dans les eaux territoriales est la durée passée dans les eaux territoriales.

Vous l'aurez compris, il y a de la redondance dans ces durées donc le temps total d'une sortie n'est pas égal à la somme des résultats des 3 lignes au-dessus.

**Comment by marthevienne** [comment]
@rv2931 pour répondre à un de tes commentaires sur une autre issue, j'ai fait un résumé du fonctionnement dans les zones et de comment calculer les durées.

**Comment by SebM42** [comment]
Pour le moment, concernant le calcul de la pêche dans des zones interdites pour un navire, on met de coté puisqu'on sait pas encore si les navires pêchent ou pas, mais on garde ces explications pour quand on le saura.

Par contre, on veut pouvoir calculer aujourd hui, par navire, et par excursion : 
- temps passé dans au moins une AMP (en h et en % de temps total) => aucun souci pour le moment, chaque segment ayant une valeur _in_amp_zone_ définissant s'il intersecte avec une amp ; seul soucis pour le moment : cette donnée n'est pas encore calculée (ticket incoming)
- temps passé dans une zone territoriale (en h et en % de temps total) => même chose que plus haut, avec la valeur _in_territorial_waters_
- temps passé dans une zone "with no fishing rights" (en h et en % de temps total) => data actuellement pas prévu à l'échelle du segment

Je propose donc qu'on : 
- recycle la colonne _in_costal_waters_ de la table fct_segment en _in_zone_with_no_fishing_rights_ 
- calcule cette valeur dans l'ETL en croisant le segment, les zones cotières, le flag du navire et les beneficiaries des zones cotières
- recycle la colonne _total_time_in_costal_waters_ en _total_time_in_zones_with_no_fishing_rights_
- calcule cette valeur dans l'ETL en faisant la somme des durées des segments de l'excursion ayant la valeur _in_zone_with_no_fishing_rights_ à 1

Autre suggestion d'un truc qu'on avait pas prévu : pour les segments taggé en DEFAULT_AIS, il serait peut-être préférable de les retirer du test d'intersection avec les zones lorsqu'ils ont une durée trop élevée (ou systématiquement, à voir), pour éviter de se retrouver avec des durées passées dans une zone énormes alors qu'on en sait en fait rien.

**Comment by marthevienne** [comment]
Manque que le détail par AMP dans ta proposition. Comment tu vois cela ? C'est déjà prévu ?

**Comment by marthevienne** [comment]
Carrément pour les DEFAULT_AIS, ça me parait judicieux de les exclure.

**Comment by SebM42** [comment]
> Manque que le détail par AMP dans ta proposition. Comment tu vois cela ? C'est déjà prévu ?

Oui, pour le détail par AMP, on a une table rel_segment_zone qui contient toutes les intersections entre zones et segments, on n'aura qu'à aggréger par AMP pour une excursion donnée

**Comment by marthevienne** [comment]
Ok, c'est clair ! Merci ! 
Je sais qu'aujourd'hui, on ne parle que de temps passé mais c'est déjà une info clé pour notre boulot !
C'est bon pour toi, pas de zone flou dans les règles ?

**Comment by SebM42** [comment]
> Ok, c'est clair ! Merci ! Je sais qu'aujourd'hui, on ne parle que de temps passé mais c'est déjà une info clé pour notre boulot ! C'est bon pour toi, pas de zone flou dans les règles ?

Ca me semble clair, il faut juste que tu nous confirmes 2 choses : 
- la table des zones est bien à jour et les noms de colonne sont tous OK
- on ignore tous les segments de type DEFAULT_AIS dans le calcul du temps passé en zone, **OU** uniquement les segments de type DEFAULT_AIS qui ont une durée supérieure à X (et définir X) ?

**Comment by marthevienne** [comment]
- la table des zones est bien à jour et les noms de colonne sont tous OK
**Non, elle n'est pas encore MAJ (attendre confirmation de Nicolas sur l'issue en question)**
- on ignore tous les segments de type DEFAULT_AIS dans le calcul du temps passé en zone, OU uniquement les segments de type DEFAULT_AIS qui ont une durée supérieure à X (et définir X) ?
**On ignore tous les segments de type DEFAULT_AIS**
