### ISSUE TITLE
[Backend] Fix coquille load_dim_zone_amp_from_csv.py

### ISSUE THREAD

**Issue by marthevienne** [dataforgoodfr/12_bloom#225]
**benificiaries to beneficiaries** !
Il faut repeupler la table dim_zone après correction.

**Comment by marthevienne** [comment]
@SebM42 la coquille a empêché que la colonne beneficiaries soit intégrée dans la table dim_zone donc pour moi, c'est du P1.

**Comment by SebM42** [comment]
ah oui en effet c est du P1 !

**Comment by njouanin** [comment]
c'est quoi le pb au juste ?

**Comment by marthevienne** [comment]
Il y a une coquille dans le code, il me semble que c'est toi qui l'avait écrit. Je peux m'en occuper mais il faudra repeupler la table dim_zones pour réintégrer le champ manquant `beneficiaries`

**Comment by njouanin** [comment]
OK, je regarde dès que possible.

**Comment by njouanin** [comment]
Bien vu pour la coquille, c'est corrigé. Par contre le traitement actuel ne prévoit pas la mise à jour ... 
il faut que je vois comment intégrer la correction dans la table dim_zone
