### ISSUE TITLE
Alerting : use case de détection d'une pêche potentielle

### ISSUE THREAD

**Issue by SaboniAmine** [dataforgoodfr/12_bloom#23]
Pour ce premier cas d'usage, et en attente de règles de détection de pêche non autorisée plus précises, nous souhaitons ajouter un système d'alerting au scrapping des données de positions récupérées sur MarineTraffic.
Voici un proposition de flow d'exécution pour ce use case : 

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/43726203/224490701-cf748712-96c0-449e-8a57-d0ceb7039564.png">

Si le scrapping fonctionne, et que le bateau se trouve dans une zone protégée, la vitesse instantanée est comparée à une valeur seuil. Si elle est inférieure à cette valeur seuil, une alerte est générée, alimentant un dossier ou rapport qui sera exporté et analysé a posteriori par l'équipe Bloom.

Cette issue est dépendante de la mise à jour des données scrappées décrites dans la #22

**Comment by RonanMorgan** [comment]
est ce que c'est également lié à cette issue ? https://github.com/dataforgoodfr/Bloom/issues/4 

Il me semble qu'on peut avoir qu'un seul module d'alerting qui puissent être déclenché par différentes "conditions" (métier comme ce use case ou plutôt technique comme de la data manquante)

**Comment by SaboniAmine** [comment]
En effet le nommage n'est pas très clair, nous avons des alertes techniques (qualité de données) & métier (détection de position / trajectoire suspecte). Il faut faire en sorte que ça soit distinct dans le code (et plus tard dans la documentation associée). A-t-on de meilleurs noms que alerte_technique et alerte_métier ?
On peut cependant tout de même les gérer en parallèle, avec plusieurs jobs exécutés par le cron, qui activeront différents use-cases, par exemple.

Par ailleurs, si ce n'était pas clair, ce premier use case n'est là que pour faire émerger la structure du code, il sera à adapter avec les règles de levée d'alerte déterminées par les data scientists notamment.
J'anticipe le fait que nous verrons apparaître plusieurs types d'objet : 
- Polygone représentant une zone protégée
- Position d'un bateau
- Alerte métier qui suspecte une position suspecte
- Règle de levée d'une alerte métier
- Rapport ou dossier (encore une fois, un nom adapté serait bienvenu)
