### ISSUE TITLE
[BACK] Faire un script SQL pour mettre a jour la table fct_excursion

### ISSUE THREAD

**Issue by SebM42** [dataforgoodfr/12_bloom#233]
2 maj à faire :
- Renommer la colonne _total_time_extincting_amp_ en _total_time_default_ais_
- calculer pour toutes les excursions existantes la valeur de _total_time_default_ais_

Rappel : _total_time_default_ais_ = somme des durées des segments de type **DEFAULT_AIS** appartenant à cette excursion

Ce script est à passer juste une fois, le calcul étant automatisé pour les excursions futures.

**Comment by njouanin** [comment]
Il faut aussi mettre à jour le traitement existant pour le flux. La modification consiste à supprimer le calcul de total_time_extincting_amp et à la remplacer par le calcul de total_time_default_ais comme étant la somme des segments de type DEFAULT_AIS

**Comment by SebM42** [comment]
je croyais que tu avais déjà fais le changement concernant le flux (cf #221 )

**Comment by njouanin** [comment]
Oui j'ai fais le changement pour total_time_extincting_amp . Là je comprends qu'il faut remplacer cette colonne total_time_default_ais dont la règle de calcul change légèrement.

**Comment by SebM42** [comment]
ah ? qu est ce qui change entre ce que j ai dit ici et en #221 ? je pensais avoir dit la meme chose, c'est juste que pour cette issue il faut renommer la colonne et faire le calcul rétroactivement avec un script

**Comment by njouanin** [comment]
tel que je l'ai compris: 
total_time_extincting_amp=somme du temps passé en DEFAULT_AIS dans une AMP (puisqu'il y a amp dans le nom de la colonne j'en ai déduis qu'il fallait compter le temps en defaut AIS uniquement lorsque le navire se trouve dans une AMP)
total_time_default_ais=somme du temps passé en DEFAULT_AIS peu importe où

**Comment by SebM42** [comment]
ah ok, en effet je me suis rendu compte un peu tard que le nom de colonne ne correspondait plus, est ce que tu peux t'occuper de modifier le code dans la task stp ? @njouanin

**Comment by njouanin** [comment]
Requête de MAJ des temps total_time_default_ais pour toutes les excursions:
```
update fct_excursion fe set total_time_default_ais = (
select sum(segment_duration) from fct_segment fs2 
where "type" = 'DEFAULT_AIS' and excursion_id = fe.id 
) 
```

**Comment by njouanin** [comment]
Le traitement [create_update_excursions_segments.py](https://github.com/dataforgoodfr/12_bloom/blob/main/backend/bloom/tasks/create_update_excursions_segments.py) a été modifié
L'historique des temps passés en DEFAUT_AIS dans chaque excursion a été recalculé sur l'ensemble des excursions en BDD.
