### ISSUE TITLE
[BACK] Modifier la task calculant l'intersection entre segments et zones

### ISSUE THREAD

**Issue by SebM42** [dataforgoodfr/12_bloom#234]
Le calcul d'intersection entre segments et zones ne se fait plus pour les segments de type **DEFAULT_AIS** (cf #224 , commentaire de @marthevienne )

Bonus : supprimer de la table _rel_segment_zone_ les segments qui sont de type **DEFAULT_AIS**

**Comment by njouanin** [comment]
supprimer également les relations existantes avec des segments DEFAULT_AIS

**Comment by njouanin** [comment]
Suppression des rel_segment_zone attachés à des segments DEFAULT_AIS:
```
delete from rel_segment_zone where segment_id in (
select id from fct_segment fs2 
where "type" = 'DEFAULT_AIS'
)
```

**Comment by njouanin** [comment]
Le traitement [create_update_excursions_segments.py](https://github.com/dataforgoodfr/12_bloom/blob/main/backend/bloom/tasks/create_update_excursions_segments.py) a été modifié pour ne plus associé aux zones les segments DEFAULT_AIS.
L'historique des rel_segment_zone associés à des segments DEFAULT_AIS a été supprimé de la BDD.
