### ISSUE TITLE
Renommage de colonnes

### ISSUE THREAD

**Issue by SebM42** [dataforgoodfr/12_bloom#237]
Relatif à l issue #224 

Dans FCT_EXCURSION renommer les colonnes : 
- _total_time_in_costal_waters_ => _total_time_in_zones_with_no_fishing_rights_
- _total_time_fishing_in_costal_waters_ => _total_time_fishing_in_zones_with_no_fishing_rights_

Dans FCT_SEGMENT renommer la colonne : 
- _in_costal_waters_ => _in_zone_with_no_fishing_rights_

**Comment by njouanin** [comment]
est-ce que ça change les règles de calcul ? ou bien c'est purement un renommage de forme.

**Comment by SebM42** [comment]
A ma connaissance, _total_time_in_costal_waters_ n'est pas calculé à ce jour

Pour ce qui est des modifs de calcul j'ai créé l'issue #238 qui englobent ces 2 calculs à faire

**Comment by ejamet73** [comment]
![Capture d’écran du 2024-11-05 15-40-49](https://github.com/user-attachments/assets/47d5514b-5f50-49c1-9790-804c8d668680)

total_time_in_costal_waters est calculé ici non ?

**Comment by njouanin** [comment]
OK, pour cet issue je ne traite que les renommages de colonnes. Pour les règles de calcul on voit ça dans l'issue #238.

**Comment by njouanin** [comment]
Fait pour le renommage des colonnes demandées
