### ISSUE TITLE
[ETL] Calcul de valeurs dans fct_segment, fct_excursion et dim_port

### ISSUE THREAD

**Issue by SebM42** [dataforgoodfr/12_bloom#238]
Calculer _in_amp_zone_ dans la table fct_segment
=> Est égal à 1 si le segment intersecte avec au moins une zone de catégorie **amp**

Calculer _in_territorial_waters_ dans la table fct_segment
=> Est égal à 1 si le segment intersecte avec au moins une zone de catégorie **territorial seas**

Calculer _in_zone_with_no_fishing_rights_ dans la table fct_segment
~~=> Est égal à 1 si le segment intersecte avec au moins une zone de catégorie **Fishing coastal waters (6-12 NM)** dont les beneficiaires n'incluent pas le pays du navire, sinon 0~~
=> Est égal à 1 si le segment intersecte avec au moins une zone de catégorie Fishing coastal waters (6-12 NM) dont les beneficiaires n'incluent pas le pays du navire OU si le segment intersecte avec au moins une zone de catégorie Clipped territorial seas <ins>**et que country_iso3 du navire est différent de FRA**<ins>, sinon 0
~~Bloqué par l'issue #275 (manque la zone dans la base)~~

Calculer _total_time_in_zones_with_no_fishing_rights_ dans la table fct_excursion
=> Est égal à la somme des durées des segments de l'excursion ayant la valeur _in_zone_with_no_fishing_rights_  égale à 1

Calculer _has_excursion_ dans la table dim_port
=> Est égal à 1 si l'id du port est utilisé comme departure_port_id ou arrival_port_id dans au moins une excursion, sinon 0

Additionnel : faire un script qui met à jour toutes ces valeurs rétroactivement dans la DB

Nécessite que #237 soit terminé pour certaines valeurs

**Comment by ejamet73** [comment]
@SebM42 mettre 0 ou 1 a quel intérets par rapport à du booleen ?

**Comment by SebM42** [comment]
Aucun, c'est une manière de dire true ou false dans ma définition, tu es libre de choisir le type de data que tu préfères

**Comment by SebM42** [comment]
en standby avant d'avoir résolu la questions des intersections de zones

**Comment by marthevienne** [comment]
Issue #275 fermée. 4 nouvelles lignes existent dans la table dim_zones de catégorie `Clipped territorial seas`.

Calculer in_zone_with_no_fishing_rights dans la table fct_segment
=> Est égal à 1 si le segment intersecte avec au moins une zone de catégorie Fishing coastal waters (6-12 NM) dont les beneficiaires n'incluent pas le pays du navire OU si le segment intersecte avec au moins une zone de catégorie **Clipped territorial seas**, sinon 0

**Comment by ejamet73** [comment]
pour "Additionnel : faire un script qui met à jour toutes ces valeurs rétroactivement dans la DB"
j'ai besoin de savoir où l'enregistrer et sous quel nom

**Comment by SebM42** [comment]
Pour tout ce qui est modification de DB, voir avec @njouanin

**Comment by SebM42** [comment]
ah zut, on a oublié un truc @ejamet73 : 

Calculer in_zone_with_no_fishing_rights dans la table fct_segment
=> Est égal à 1 si le segment intersecte avec au moins une zone de catégorie Fishing coastal waters (6-12 NM) dont les beneficiaires n'incluent pas le pays du navire OU si le segment intersecte avec au moins une zone de catégorie Clipped territorial seas <ins>**et que country_iso3 du navire est différent de FRA**<ins>, sinon 0

**Comment by ejamet73** [comment]
Ok @SebM42 , autre remarque, pour l'instant on considère pas les intersection de segments avec des zones mais des inclusions des segments dans les zones grâce à ST_Within, dois-je changer pour ST_Intersects ?

**Comment by SebM42** [comment]
Nope c'est parfait, on garde la même logique partout, et c'est celle que marthe souhaite
