### ISSUE TITLE
[DASHBOARD] Erreur dans le calcul et données dynamiques à envoyer au front

### ISSUE THREAD

**Issue by SebM42** [dataforgoodfr/12_bloom#245]
![image](https://github.com/user-attachments/assets/560b2052-5f87-4fdc-aab5-cc92a48eb446)

### Total vessel in activity : 
Numérateur : Corriger le calcul
Rappel : représente le nombre de navires **uniques et actifs** qui ont participé à au moins 1 excursion dans la plage de temps donnée
--> ajouter un endpoint pour avoir les valeurs (juste un chiffre) 

--> pour l'instant on garde le dénominateur fixe. 

### Total amp visited : 
Dénominateur : Valeur dynamique à envoyer au front
Rappel : représente le nombre total de zones de catégories **amp** dans la base
--> ajouter un end point pour avoir les valeurs.  (juste un chiffre)

**Comment by rv2931** [comment]
Je viens de regarder le code, la valeur 10000 vient d'une valeur par défaut quand il n'y avait pas les endpoints
J'ai l'impression que ce n'est plus le cas, ça ne devrait donc plus être 10000 maintenant
par contre pour les devs qui utilisent la stack Docker, il faut rebuild le conteneur frontend pour toutes les mises à jour frontend
J'ai de recompiler le frontend de mon côté voir si c'est toujours 10000
D'ailleurs c'est un peu bizarre 10000 comme valeur par défaut, je proposerais soit un ? ou - ou éventuellement -1 si ça doit être un entier mais pas 10000

**Comment by louwelgryn** [comment]
assez d'accord que ca serait bien une valeur par défaut qui nous laisse comprendre que ca n'est pas de la vrai donnée. 
? c'est pas mal ;)

**Comment by marthevienne** [comment]
Done !

Note : j'ai corrigé le code dans la PR #287 mais la méthode en soit n'est pas utile comme on en a parlé au weekly. On récupère en sortie la liste des navires qui ont fait au moins une excursion pendant une plage de temps donnée avec le temps en mer associé. On n'en a pas besoin donc supprimer ce endpoint en le détournant vers l'issue existante pour retourner un nombre, pas une liste.

**Comment by marthevienne** [comment]
Hello @rv2931, qui s'occupe des endpoints ?

**Comment by rv2931** [comment]
Je suis en train de regarder : https://github.com/dataforgoodfr/12_bloom/pull/298
Là a partir d'un dump de cette semaine, je ne trouve des zones visitées qu'au mois de novembre (44)
Faut que je regarde les données d'un peut plus près pour voir si c'est cohérent ou non

**Comment by marthevienne** [comment]
Hello @rv2931, je m'occupe de l'endpoint activityCount sur le modèle de ce que tu as fait pour trackedCount
