### ISSUE TITLE
[DASHBOARD] Durées en Xd Xh Xmin

### ISSUE THREAD

**Issue by SebM42** [dataforgoodfr/12_bloom#248]
Hello @alexphiev, yes, on peut convertir les heures en jours et heures comme ce qu'a fait @HenriChabert dans le panel de synthèse en mode trajectoire

**Comment by alexphiev** [comment]
@SebM42 Tu veux dire que 2500360 devient 2 500 360 (FR)? ou 2,500,360 (US)? D'ailleurs je devrais peut être convertir les heures en jours et heures ?

**Comment by SebM42** [comment]
En effet j'ai oublié de préciser quel séparateur : on prends le séparateur FR

@marthevienne à toi de voir pour la conversion en jours

**Comment by marthevienne** [comment]
Hello @alexphiev, yes, on peut convertir les heures en jours et heures comme ce qu'a fait @HenriChabert dans le panel de synthèse en mode trajectoire

**Comment by alexphiev** [comment]
Done!
