### ISSUE TITLE
[DASHBOARD] Top 10 par zones/navires

### ISSUE THREAD

**Issue by SebM42** [dataforgoodfr/12_bloom#249]
Description : panel qu'on atteint lorsqu'on clique sur un des boutons "view" du top 5

![image](https://github.com/user-attachments/assets/1f458e96-12c6-4db0-af71-3d84799a8151)

### TOP 10 PAR ZONE (lorsqu'on clique sur "view" d"une zone)

Maquette : 

![image](https://github.com/user-attachments/assets/4afbb21d-34f1-481c-96ad-b4d0ecaa8b19)

A : bouton pour revenir à l'écran précédent

B : nom de la zone sur laquelle on a cliqué

C : carte centrée sur la zone avec niveau de zoom permettant d'englober la totalité de la zone dans la fenêtre
**Laisser un espace vide pour le moment, cette partie est à priorité très basse. Fera l'objet d'un autre ticket spécifique pour cette tache**

D : top 10 des navires ayant passé le plus de temps dans la zone, trié du plus de temps au moins de temps

![image](https://github.com/user-attachments/assets/aeebf375-36d7-447b-8da8-1f91af688fb7)

E : nom du navire

F : imo/ mmsi/ type / length_class

G : temps total passé dans la zone, en heure

### TOP 10 PAR NAVIRE (lorsqu'on clique sur "view" d"un navire)

même présentation que pour les zones

B : nom du navire sur lequel on a cliqué

C : photo du navire
**Indisponible pour le moment, laisser un espace vide. Fera l'objet d'un autre tocket spécifique pour cette tache**

D : top 10 des zones de type AMP dans lesquelles le navire a passé le plus temps, trié du plus de temps au moins de temps

E : nom de la zone

F : **à définir** @marthevienne 

G : temps  total passé dans la zone de type AMP, en heure

@alexphiev si tu n'as pas les data nécessaires dans les requetes API dispo, n'hésite pas à le faire savoir

**Comment by alexphiev** [comment]
@SebM42 @louwelgryn  Il me manque quelques données des vessels pour la vue "top 10 par zone". 
J'utilise le endpoint `/metrics/zones/${zoneId}/visiting-time-by-vessel` et je reçois une liste de ce type, sans imo et mmsi:
```json
[
  {
    "zone_id": 660,
    "zone_category": "amp",
    "zone_sub_category": "Special Protection Area (Birds Directive)",
    "zone_name": "Mers Celtiques - Talus du golfe de Gascogne",
    "vessel_id": 8,
    "vessel_name": "ADVIENTO UNO",
    "vessel_type": "Other",
    "vessel_length_class": "25-40 m",
    "zone_visiting_time_by_vessel": "PT17M45S"
  }
]
```

**Comment by louwelgryn** [comment]
@rv2931 aussi ? ;)

**Comment by SebM42** [comment]
bloqué par l'issue #272

**Comment by alexphiev** [comment]
Bloqued by https://github.com/dataforgoodfr/12_bloom/issues/273

**Comment by rv2931** [comment]
#272 et #273 ont été faites et livrées

**Comment by marthevienne** [comment]
On peut fermer ?

**Comment by alexphiev** [comment]
Yes!
