### ISSUE TITLE
[MAP] Modifier infos tooltip navire

### ISSUE THREAD

**Issue by marthevienne** [dataforgoodfr/12_bloom#258]
Modifier les infos sur le tooltip : 
- ship_name (vessel)
- mmsi (vessel)
- type (vessel)
- length (vessel)
- timestamp en UTC mis en forme (position)

PHOTO DU NAVIRE PAS PRIORITAIRE (on n'a pas encore de procédure pour les images, laisser un placeholder)
<img width="300" alt="Capture d’écran 2024-11-14 à 11 55 16 PM" src="https://github.com/user-attachments/assets/766d03f9-d51b-4858-bd71-ad74b661b601">

**Comment by SebM42** [comment]
L'image du flag n'est également pas prioritaire, pour le moment indiquer juste le code country_iso3

Reste à faire : timestamp en UTC mis en forme

**Comment by louwelgryn** [comment]
Donc la concrètement il ne reste que à mettre " timestamp en UTC mis en forme et code country_iso3 à afficher à la place du flag" tout le reste est bon on est d'accord ? @SebM42 @marthevienne
