### ISSUE TITLE
[MAP] Tooltip et popup sélection navires

### ISSUE THREAD

**Issue by marthevienne** [dataforgoodfr/12_bloom#259]
@HenriChabert j'ai complété le ticket parce que je ne le trouvais pas assez complet. Merci ! 

**Informations dans le tooltip/popup**
    - placeholder (image du bateau dans le futur)
    - country_iso3*
    - ship_name*
    - mmsi*
    - type*
    - length*  
    - timestamp* (à mettre en forme en UTC) | exemple : 16/04/2023 - 12:23:00 (UTC)

*À choper dans le endpoint **/vessels/all/positions/last**

**Au hover sur un bateau**
<img width="400" alt="Capture d’écran 2024-12-12 à 11 35 00 AM" src="https://github.com/user-attachments/assets/24b44c94-554f-4c48-aacd-2d2ec2b9fd3b" />
- la card avec le bateau apparait (ancre top left) 

**Au clic sur le bateau**
BONUS : popup draggable :) 
![Capture d’écran 2024-12-12 à 4 26 29 PM](https://github.com/user-attachments/assets/505712c4-f1c6-4127-9ed4-1bfe7abfddfc)

Validé ne pas tenir compte des commentaires.

**Comment by SebM42** [comment]
@marthevienne 
On a une divergence entre le comportement en prod et ce qui a été designé, je te propose ceci : 
- on garde l'affichage de la pop-up en mouseover sur l'icone (actuellement en prod) ; la pop-up disparait en mouseout
- on n'utilise plus la croix sur fond vert pour ajouter un navire à la sélection, mais un clic gauche sur le navire
- on peut désélectionner un navire préalablement sélectionné en recliquant dessus
- on ajoute un élément dans la pop-up (bandeau, etc.) indiquant qu'un navire est sélectionné
- on highlight l'icone d'un navire lorsqu'il est sélectionné (glow, border, etc.)
- on supprime la pop-up qui apparait en bas à droite suite à un clic, qui est redondante et obsolète
- la pop-up est ancré sur la partie milieu-bas (maquette) et non plus sur la partie gauche-haut (prod)

Qu'en penses-tu ?

**Comment by marthevienne** [comment]
- on garde l'affichage de la pop-up en mouseover sur l'icone (actuellement en prod) ; la pop-up disparait en mouseout
OK

- on n'utilise plus la croix sur fond vert pour ajouter un navire à la sélection, mais un clic gauche sur le navire
OK

- on peut désélectionner un navire préalablement sélectionné en recliquant dessus
OK

- on ajoute un élément dans la pop-up (bandeau, etc.) indiquant qu'un navire est sélectionné
Est-ce que c'est utile en plus d'un signe distinctif sur l'icône ?

- on modifie l'icone d'un navire lorsqu'il est sélectionné (glow, border, couleur de l'icone, etc.)
OK

- on supprime la pop-up qui apparait en bas à droite suite à un clic, qui est redondante et obsolète
OK

- la pop-up est ancré sur la partie milieu-bas (maquette) et non plus sur la partie gauche-haut (prod)
OK

**Comment by louwelgryn** [comment]
Hello ! 
Désolée mais je ne pense pas qu'un clique gauche soit une bonne idée - c'est pas une bonne pratique de faire des modifications sans boutons qui t'indiquent comment faire. 
Je propose plutot : 
- De rajouter un bouton 'Select Vessel' - quand on clique dessus il est ajouté - quand on clique dessus il se transforme en 'Unselect Vessel' (voir peut changer de couleur genre rouge pour qu'on comprenne) 
- On garde le bouton 'Show tracks' - qui permet de passer en mode trajectoire 

On peut juste mettre une autre couleur pour les bateaux qui sont selectionnés, pas la peine de mettre une couleur en plus sur la pop up ca fait trop je pense ;)

SI ça vous va je modifie le corps du ticket pour valider ça définitivement ;)
@marthevienne

**Comment by marthevienne** [comment]
@louwelgryn le bouton `Select vessel` serait sur le popup qui s'affiche quand on clique sur le bateau ? Et le bouton `Show tracks` serait toujours dans le panel à gauche ?

**Comment by marthevienne** [comment]
@HenriChabert je crois que c'est bien clair pour toi mais je peux clarifier encore cette issue ;)

**Comment by HenriChabert** [comment]
Hello @marthevienne, c'est tout à fait clair ! Jwe n'ai pas encore eu le temps de m'y mettre mais la journée demain est dédiée à finaliser tous ces points :)
