### ISSUE TITLE
[MAP] Box calques

### ISSUE THREAD

**Issue by marthevienne** [dataforgoodfr/12_bloom#263]
Box disponible en mode trajectoire + position. 
 en haut à droite pour filtrer les zones affichées sur la carte (uniquement par catégorie) :

<img width="365" alt="Capture d’écran 2024-11-25 à 11 12 51 AM" src="https://github.com/user-attachments/assets/fbb960b5-08c5-4a3c-a3c5-a9c71cf1d1a1">

Association textes box et catégories en base :
- `Territorial waters` = `Territorial seas`
- `Fishing coastal waters` = `Fishing costal waters (6-12 NM)`
- `MPA` = `amp`

**Comment by SebM42** [comment]
Etant donné la deadline du 19/12, on va commencer par afficher les geometries des zones telles quelles, sachant que par défaut au lancement de l'appli, les zones ne seront pas affichées pour éviter l'éventuelle surcharge

Si ca te va, tu afficheras plus ou moins de zones avec les filtres à ta disposition et tu nous feras un retour sur les performances, et on avisera ensuite.

Le point sur le show/hide est traité dans l'issue #264

Le point sur l'interactivité des zones va devoir être passé en P3 car il y a beaucoup de choses qui n'ont pas été designés/discutés, notamment le comportement dans le cas où plusieurs zones se chevauchent/s'incluent. On va se concentrer sur l'affichage des zones pour le moment, avec une distinction de couleur pour chacune des 3 catégories de zones : AMP, TERRITORIAL, COASTAL

**Comment by SebM42** [comment]
Pour @alexphiev : 
P1 : affichage des polygones des zones sur la map avec une distinction de couleur en fonction des 3 catégories de zones : 
amp : [couleur à venir]
Territorial seas : [couleur à venir]
Fishing coastal waters (6-12 NM) : [couleur à venir]

bloqué par l'issue #271



Pour @marthevienne @SebM42 et Paul : 
P3 : réfléchir à l'interaction de l'utilisateur avec les zones affichées et au comportement de l'appli subséquent

**Comment by marthevienne** [comment]
@alexphiev NB : map super fluide avec des milliers de polygones ici : 
https://mpatlas.org/mpaguide/

**Comment by louwelgryn** [comment]
ca on peut considérer que c'est done ? ;)

**Comment by marthevienne** [comment]
Tout dépend si on n'attend pas les couleurs + si on laisse tomber la discussion sur la géométrie des eaux territoriales  pour l'instant (polygone ou limite)

**Comment by louwelgryn** [comment]
En fait j'avais créé un autre ticket pour les couleurs 

Mais du coup oui il reste à changer les couleurs et en avoir 3 
AMP
Terrestrial 
Costal

**Comment by marthevienne** [comment]
En attente d'une proposition de Paul

**Comment by alexphiev** [comment]
En fait il manque la box de filtre en question :D

**Comment by alexphiev** [comment]
Rien :D
Je fais la box de filtre et je clos cette issue.

**Comment by louwelgryn** [comment]
haha top

**Comment by alexphiev** [comment]
Fait. Sera déployé avec https://github.com/dataforgoodfr/12_bloom/pull/334
