### ISSUE TITLE
[TRAJECTOIRE] Box options

### ISSUE THREAD

**Issue by marthevienne** [dataforgoodfr/12_bloom#264]
En mode trajectoire uniquement :

<img width="382" alt="Capture d’écran 2024-11-25 à 11 12 41 AM" src="https://github.com/user-attachments/assets/1faedb2c-6465-45c6-b6eb-059bbe276376">

**Mode speed/vessel:** 
Inclus tous les bateaux selectionnés.
- `speed` : les trajectoires se colorent en fonction de la vitesse et une légende apparait en bas a droite
- `vessel` est sélectionné : chaque bateau voit sa trajectoire d'une seule couleur. 

A DEFINIR : Précision sur le end point à prendre. 

la palette des trajectoires de couleur est disponible ici : 
<img width="582" alt="Capture d’écran 2024-11-29 à 12 58 18 PM" src="https://github.com/user-attachments/assets/fdc24d27-314d-4e0d-a810-cf7560625a2c">
A DEFINIR : Précision sur le end point à prendre. 

https://www.figma.com/design/MNnJ7bfa4tS7txveGikQOx/Bloom-Trawlwatch-(DEF)?node-id=338-2954&node-type=canvas&t=viczrHUFzoVvo1vX-0
V4 - frame 241. 

**Display positions:**
Quand le toggle est _on_ on peut voir tous les points de position : 
          - quand les positions sont données mettre une icone bateau
          - quand les positions sont inexistantes mettre l'icone correspondante au fait de ne pas avoir de position. 
          - A DEFINIR : Précision sur le end point à prendre. 

<img width="400" alt="Capture d’écran 2024-11-25 à 4 21 23 PM" src="https://github.com/user-attachments/assets/983b3a21-b2ad-4467-ac17-0f5f87f11cab">

**Comment by louwelgryn** [comment]
@marthevienne @SebM42 je vous laisse relire pour être surs qu'il y a toutes les infos et on passe en done quand vous validez ;)

**Comment by louwelgryn** [comment]
Une autre question que je me posais en voyant cette image : sur quelle période affche-ton les trajectoires ? estce que ca c'est défini ?

**Comment by marthevienne** [comment]
@louwelgryn Paul n'a pas modifié l'icône calques et à laisser l'icône options. À changer :)
Pour ce qui est de la faisabilité de cette issue pour le 19, je crois que @SebM42 et @alexphiev ont des doutes.

**Comment by SebM42** [comment]
> @louwelgryn Paul a mis les options de visualisation avec les calques. Je m'en occupe pour faire comme on avait dit en réunion il y a 1 mois. Pour ce qui est de la faisabilité de cette issue pour le 19, je crois que @SebM42 et @alexphiev ont des doutes.

Oui, je baisse la prio, y a d'autres fonctionnalités plus importante que celle ci à gérer avant

**Comment by marthevienne** [comment]
@HenriChabert je ne sais pas s'il te reste des choses à faire mais voici une issue sur lequel tu peux bosser si t'as du temps
