### ISSUE TITLE
[POSITION] Box filtres

### ISSUE THREAD

**Issue by marthevienne** [dataforgoodfr/12_bloom#265]
Uniquement en mode position, pouvoir filtrer les navires sur la carte
- length_class
- country_iso3
- type

Modal s'ouvre au niveau du bouton (coin en haut à droite)

<img width="230" alt="Capture d’écran 2024-11-15 à 12 34 40 AM" src="https://github.com/user-attachments/assets/91ef08e4-8a9f-4e07-98fe-97aac02beff2">

**Comment by alexphiev** [comment]
Livré en prod !
