### ISSUE TITLE
[POSITION]  - Left panel et barre de recherche. 

### ISSUE THREAD

**Issue by marthevienne** [dataforgoodfr/12_bloom#266]
### Résumé :

- [x] barre de recherche => position expand + clic sur item dans la liste
- [x] comportement icône navire recherche via searchbar
- [x] comportement de selected vessels
- [x] boutons create fleet et show tracks
- [x] comportement nav bar rétractée => couleur à revoir @HenriChabert 

### Détails : 
Aller le chercher dans la V4 - frame 'Left Panel Final'
<img width="512" alt="image" src="https://github.com/user-attachments/assets/4dd6dafe-daa4-4227-b9d0-c269d127182d">

1) Afficher la barre de recherche comme dans la maquette - et la rendre fonctionnelle avec les modifications suivantes : 
- faire fonctionner la barre de recherche comme dans google 

<img width="400" alt="image" src="https://github.com/user-attachments/assets/a3eb9bdf-e6b1-449d-aba3-84ed2b5ba12d">

c'est à dire : 
quand on clique dans la barre elle s'autoexpand - on peut taper dedans et la recherche s'actualise avec les nouveaux mots - et ensuite on clique sur entrée pour chercher. (supprimer le bouton de search en vert.
- quand on clique sur un navire dans la liste - la recherche centre la carte sur le bateau qui s'entoure d'une couleur flashy pour le reconnaitre. Attention, le navire n'est pas encore sélectionné, il faut cliquer dessus sur la carte.
<img width="200" alt="Capture d’écran 2024-11-29 à 1 01 04 PM" src="https://github.com/user-attachments/assets/4700ed49-9d32-4262-820f-778dcfab4680">

=> Pour voir le comportement des icônes des navires (voir #259).

2) Lorsqu'on sélectionne un navire, il s'ajoute dans le panel de gauche sous "Selected vessels". Le nombre de navires sélectionnés est affiché à côté de "Selected vessels".
<img width="200" alt="Capture d’écran 2024-12-03 à 10 26 28 AM" src="https://github.com/user-attachments/assets/3058ddf7-eea7-4aed-a2be-76231b61a822">

```
VESSEL.SHIP_NAME
vessel.imo / vessel.mmsi / vessel.length
```
Comportement x : supprime le navire de la sélection.

3) Ajouter les boutons `Create fleet` et `Show tracks`
- `Create fleet `---> on ajoute le bouton mais en grisé car il est inactif
- `Show tracks` (modifier le texte View tracks par Show tracks)- nous fait passer en mode trajectoire, par défaut une couleur par navire, par défaut sur les 15 derniers jours.
Le bouton `Show tracks` est grisé et inactif si aucun navire n'est sélectionné

cf #215 pour le passage du panel en mode trajectoire

4) Quand la barre de gauche est retractée il faut qu'elle ressemble à ca : 
<img width="211" alt="image" src="https://github.com/user-attachments/assets/71f5b559-efb2-4dc9-b193-a363a7de9eaf">

**Comment by alexphiev** [comment]
@marthevienne Désolé mais je suis pas sûr de comprendre ce que tu veux sur la barre de recherche. Déjà, de quelle frame figma parles-tu ? "MODE POSITION - HOMEPAGE" ? J'ai besoin de savoir ce qu'il y a à changer par rapport à ce qui existe en prod en ce moment. 

On a déjà la barre qui s'expand et la recherche s'actualise déjà avec la recherche de mots. À moins que tu t'attendes à autre chose ? 
Par contre c'est sûr qu'il manque le fait de pouvoir cliquer sur un résultat, et la mis en valeur d'un navire choisi mais "non sélectionné" et juste centré et mis en surbrillance.

**Comment by marthevienne** [comment]
Hello @alexphiev , on voudrait que la barre de recherche s'expand là où tu cliques comme pour la barre de recherche de Google. On n'a pas de composant figma pour ça.

**Comment by alexphiev** [comment]
Done ! Peux-tu confirmer que c'est ce que tu voulais ? :)

**Comment by marthevienne** [comment]
Hello ! Tu l'as déployé en prod ?

**Comment by alexphiev** [comment]
En cours, prêt dans 5 min. 
@HenriChabert est-ce que tu t'occupes déjà de ça ou je le fais ? 

> quand on clique sur un navire dans la liste - la recherche centre la carte sur le bateau qui s'entoure d'une couleur flashy pour le reconnaitre. Attention, le navire n'est pas encore sélectionné, il faut cliquer dessus sur la carte.

**Comment by marthevienne** [comment]
Possible de faire en sorte que la liste soit en position absolue ? Càd la position des éléments du panel ne bouge pas, le composant se superpose sur le panel. Comportement classique d'une barre de recherche.
