### ISSUE TITLE
[API] Data sur les navires pour le dashboard

### ISSUE THREAD

**Issue by SebM42** [dataforgoodfr/12_bloom#273]
Vu avec @alexphiev : on n'a pas trouvé d'enpoint permettant de récupérer le top 10 des zones traversées par un navire

Pour rappel, on souhaite avoir un endpoint similaire à **visiting_time_by_vessel** qui retourne des datas de zone avec la structure suivante : 

```
[
  {
    "vessel_id": 0,
    "vessel_name": "string",
    "zone_id":0,
    "zone_category": "string",
    "zone_sub_category": "string",
    "zone_name": "string",
    "zone_visiting_time_by_vessel": "P3D"
  }
]
```

**Comment by rv2931** [comment]
Principe validé avec @alexphiev . Je tente la livraison et faudra valider ça en weekly

**Comment by rv2931** [comment]
Livré en prod: https://app-50bfd872-632e-4cb6-abc2-b94479db4d03.cleverapps.io/docs#/Metrics/read_metrics_all_vessels_visiting_time_by_zone_api_v1_metrics_vessels_time_by_zone_get
@alexphiev

**Comment by marthevienne** [comment]
On n'en a pas parlé en weekly. Je ne crois pas que ça réponde aux besoins.

**Comment by alexphiev** [comment]
Ça m'a servit pour la page de détails des top amps visitées par un bateau. https://github.com/dataforgoodfr/12_bloom/pull/336
