### ISSUE TITLE
CD: workflow GA pour déployer sur l'environnement Scaleway

### ISSUE THREAD

**Issue by SaboniAmine** [dataforgoodfr/12_bloom#28]
Afin de suivre les mises à jour du scrapping des données de positions de bateau, il serait intéressant de pouvoir déployer automatiquement l'application sur la machine scaleway à disposition.
Une première étape serait de pouvoir build l'image docker dans le job build & test, puis d'avoir une autre action qui déploie cette image docker.

**Comment by RonanMorgan** [comment]
du coup l'idéal ce serait de faire ça directement sur le K8S

**Comment by SaboniAmine** [comment]
Yes ça me va. 
Pour la deuxième tâche il faudrait que ça soit une action manuelle, et nous devrons nous synchro avec Paul Gabriel pour voir quel est le meilleur moyen de déployer un service sur le cluster provisionné.

**Comment by RonanMorgan** [comment]
il a mis un argoCd mais effectivement j'aurais aimé faire ça juste après le début de la saison 11 (j'ai encore plein de réunion semaine pro pour finir la préparation :/

**Comment by mnicolleUTC** [comment]
Salut tous le monde, j'étais un peu en mode sous-marin les dernières semaines mais là c'est bon j'ai de nouveau des dispo courant de semaine pro. L'issu me plaît bien donc je peux essayer de regarder ca courant de semaine prochaine si ça vous va. Bonne journée :)

**Comment by RonanMorgan** [comment]
cool ! L'idée c'est qu'on passe rapidement sur K8S donc si t'es chaud la première step ça peut être une gitAction qui build l'image docker et qui l'héberge sur le GitHub de D4G

**Comment by RonanMorgan** [comment]
tu peux simplement lancer une commande "docker build" (ie pas besoin de créer un fichier 

un exemple de step gitAction de mon taf :
`      - name: Install dependencies locally
        working-directory: ./deployment/automation
        run: make pip ansible deps`
        
et oui je vais t'envoyer le token sur slack

**Comment by SaboniAmine** [comment]
Pour le token pas besoin de le partager, il suffit de le déclarer dans la variable `GITHUB_TOKEN` par `[ici](https://github.com/dataforgoodfr/Bloom/settings/variables/actions)`.
A ne pas afficher dans les actions avec la commande `echo`, car les logs sont accessibles à tous :)

**Comment by RonanMorgan** [comment]
alors justement en mp j'ai envoyé cette doc à Mathieu : https://docs.github.com/en/actions/security-guides/automatic-token-authentication

tu es sûr qu'il faut la déclarer ? j'ai l'impression qu'un token est créé automatiquement pour chaque gitAction. A tester peut être.

**Comment by SaboniAmine** [comment]
Je viens de tester et tu as raison, la variable n'a pas besoin d'être déclarée au préalable pour être utilisée!

**Comment by mnicolleUTC** [comment]
Bonjour à tous, 

Après un long temps d’attente je viens de faire une PR pour la première étape de l’issu #28 CD: workflow GA pour déployer sur l'environnement Scaleway. La première étape consistant en la création d ‘ « une gitAction qui build l'image docker et qui l'héberge sur le GitHub de D4G »

J’ai du faire plusieurs commit car j’ai toucher à pas mal de chose différente lors de cette PR :
Commit :

feat: Add container build and push to GA —> Concerne le coeur de la PR qui permet de build et push automatiquement le container docker. J’ai fait des tests concluants dans un dummy repo (https://github.com/mnicolleUTC/demo_github_action_CICD) donc normalement il n’y a pas d’erreur mais on ne sait jamais….

fix: Changes on docker container to fix the build —> Obligatoire car je pense qu’on avait un peu modifié à la volée le Dockerfile qui sera l’image hébergé sur D4G, notamment en essayant de le build en local, le container me renvoyer directement une erreur d’import pour aller chercher le package bloom/enums.py car en fait l’instruction bloom/ . va copier le contenu du dossier Bloom à la racine du container au lieu de copier le dossier à la racine du container. Ce qui fait un peu fouillis et conduit à une erreur lors de l’import des packages spécifique Bloom. J’ai donc changé par COPY bloom/ ./bloom/ (idem pour le dossier data du coup). 
Ensuite j’ai également du update la version de poetry utilisé pour être cohérente avec celle du fichier poetry.lock: « # This file is automatically @generated by Poetry 1.4.0 and should not be changed by hand. » Et enfin j’ai supprimé la ligne README.md du fichier pyproject.toml car le fichier n’étant pas copier dans le docker j’avais également une erreur [Errno 2] No such file or directory: '/README.md'
------ executor failed running [/bin/sh -c poetry install]: exit code: 1

refactor: Choosing base image python3.10-slim for container : Petit changement dont on avait parlé pour alléger l’image docker en se basant sur python-3.10-slim qui nécessite l’installation manuelle de wget et poetry run python3 app.py en commande pour l’ENTRYPOINT. Ce point là il me semble qu’on en avait discuté et on avait garder ta solution Amine de juste mettre python3 app.py mais là en basculant sur l’image slim j’ai eu cette erreur donc j’ai corrigé avec ma solution mais on peut en discuter. 

doc: Update of README.md file : Update du readme file pour decrire les différentes modifications sur les containers. 

fix: Define env variables for container push —> C’était un oubli de ma part lors du push du fichier build.yaml car j’avais oublié de définir des variables d’environnement qui permettent le push du container. 

Pour info, j’ai un bug lors de l’execution du build.yaml mais pour une histoire de permissions donc je suis preneur de votre avis : @Amine et @ Ronan. Je pense que 95% de l’étape 1 est terminée mais je veux bien un peu de conseil pour ce dernier problème vu que j’ai des droits assez réduit sur le repo Bloom. 

Voilà n’hésitez pas à me dire ce que vous en pensez directement sur la PR même si encore en bug et n’hésitez pas je suis preneur de tout les conseils ou best practice que je n’aurais pas fait lors de l’ajout de la GA (c’était une première pour moi). 


Bonne journée à tous.

**Comment by RonanMorgan** [comment]
ah pardon j'avais oublié ton commentaire concernant les droits. J'ai déjà commenté mais je vais creuser encore un peu
