### ISSUE TITLE
[FRONT] - pas les dernières positions des bateaux disponibles. 

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_bloom#284]

**Comment by alexphiev** [comment]
J'ai ajouté un cache côté front d'une heure au lieu d'un cache infini comme c'était le cas (le cache est côté **serveur front**, donc refresh du navigateur ne changera pas les données retournées). Ça te va @marthevienne ? Ou tu veux qu'on ait la donnée actualisée à chaque refresh ?

**Comment by marthevienne** [comment]
#262 C'est lié à cette issue. On n'a pas pris de décision pour l'instant. Il faut qu'on puisse avoir la donnée la plus récente (toutes les 15 min pour le call à Spire + ETL).
C'est possible de mettre un cache d'1/4h pour l'instant ?
