### ISSUE TITLE
[API] Internal Server Error segments

### ISSUE THREAD

**Issue by alexphiev** [dataforgoodfr/12_bloom#288]
J'ai une error 500 Internal Server Error en testant le endpoint `/vessels/387/excursions/101693/segments`. Ça explique le fait que la dernière trajectoire des bateaux ne s'affichent pas.

**Comment by rv2931** [comment]
je vais regarder ça

**Comment by rv2931** [comment]
Ok. C'est temporairement corrigé par les PR #290 et #292 
Faut statuer sur les valeurs NaN/INF en attendant ça renvoie null

**Comment by alexphiev** [comment]
Je confirme que ça ne plante plus !
