### ISSUE TITLE
[MAP] - ajouter les nouvelles couleurs des zones 

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_bloom#289]
Il existe maintenant 4 catégories de zones :
- [ ]  `Fishing coastal waters (6-12 NM)` : 
     - fill : #840000 - 10% opacité
     
- [ ] `amp` : 
     - fill : #1EE0AB  - 10% opacité
     - border : 1px dashed #2CE2B0
     
- [ ] `Territorial seas` :
     - border : #840000 
     - fill : transparent
     
- [ ] `Clipped territorial seas`: jamais affichées sur la carte (utilisées pour les calculs)

NB : pour l'instant, on a que des polygones en base. On verra pour afficher une limite  (une ligne plutot que des polygones) pour `Territorial seas` plus tard
![Capture d’écran 2024-11-27 à 5 13 28 PM](https://github.com/user-attachments/assets/9034a8ab-2ec8-4623-b2d3-fbd99eb392ec)

**Comment by marthevienne** [comment]
Je faisais des tests mais Paul bosse encore dessus

**Comment by alexphiev** [comment]
Voici le résultat. L'ajout de contours rend la carte moins réactive malheureusement, encore plus en dashed potentiellement.
<img width="1251" alt="image" src="https://github.com/user-attachments/assets/b73c9292-3189-4311-87ae-96c4db0b23f0">

**Comment by marthevienne** [comment]
Qu'est-ce que tu veux dire par réactive ?

**Comment by alexphiev** [comment]
C'est moins fluide lorsqu'on se déplace sur la carte à cause des bords et remplissages des zones qui sont très complexes.

**Comment by marthevienne** [comment]
@alexphiev je suis d'accord, c'est pas génial donc tu peux laisser en solide pour l'instant

**Comment by alexphiev** [comment]
J'ai dû enlever les contours car le fait qu'ils soient solides ou pointillés ne change pas vraiment niveau perf. Les deux font ralentir significativement la carte. Qu'en penses-tu ? On pourra trouver un moyen d'amléliorer ça dans le futur.
