### ISSUE TITLE
[BACK] Disparition des données Relation Segment Zone avant le 19/11/2024

### ISSUE THREAD

**Issue by rv2931** [dataforgoodfr/12_bloom#299]
Détecté dans le cadre de l'issue #286 Nous nous sommes rendu compte que les données faisant la relation entre les zones et les segments n'a plus de données avant le 19/11/2024, ce qui rend de fait toute recherche de relation avant caduque ( #286  passe en attente du coup)
Pas d'explication à la disparition de ces données pour le moment
CleverCloud fait un backup journalier de la base mais on s'en est rendu compte trop tard pour récupérer un backup avant

**Comment by marthevienne** [comment]
C'est ma faute, j'ai modifié la table dim_zones le 19...

**Comment by rv2931** [comment]
A tout hasard t'as pas une sauvegarde de "juste avant" ?

**Comment by marthevienne** [comment]
Non... Mon dernier dump du 30/10

**Comment by marthevienne** [comment]
Il y a encore pas mal d'erreurs dans la tâche de création de segments et des excursions (durées aberrantes, spoofing qu'on peut éviter, temps mal calculés dans les zones). Ça pourrait me forcer à m'en occuper maintenant.

**Comment by rv2931** [comment]
Avec @njouanin je pense qu'il y a moyen de réintégrer les infos de relation zones telles qu'elles était jusqu'au 30/10
Et de toutes façons si grosse modification du traitement des zones faudra a mon avis tout supprimer et tout recalculer

**Comment by marthevienne** [comment]
Désolée pour la grosse erreur !

**Comment by rv2931** [comment]
Au début j'avais émis l'idée de gerer la dim_zone en Slow Changing Dimension pour garder un historique même avec des évolutions de zone par contre cette solution implique une méthode de mise a jour un peu plus complexe mais sans perte d'info et en gardant un historique cohérent même avec les stats. Je lance la question. C'est pas urgent mais en terme de qualité c'est un plus

**Comment by marthevienne** [comment]
J'ai supprimé toutes les données de la table dim_zone et repeupler 🤡 

=> S'il faut tout recalculer, attention on n'a plus toutes les données brutes dans spire_ais_data. Par contre dans vessel_positions on a tout. Donc il n'y aurait qu'à corriger le traitement create_update_excursions_segments.py, vider les tables fct_segment et fct_excursion, et relancer le traitement depuis le mois d'avril.
**Yes, on va pouvoir repartir de `vessel_positions` sans problème.**

=> Par contre ça risque d'être trèèèèèès long donc il faudra traiter par lots d'intervalles de dates je pense.
**Yes, j'ai déjà capteé qu'il fallait y aller de manière incrémentable. Je vais essayer par lot d'une semaine.**

=> Au début j'avais émis l'idée de gerer la dim_zone en Slow Changing Dimension pour garder un historique même avec des évolutions de zone par contre cette solution implique une méthode de mise a jour un peu plus complexe mais sans perte d'info et en gardant un historique cohérent même avec les stats. Je lance la question. C'est pas urgent mais en terme de qualité c'est un plus.
**Carrément, on a bien cette évolution-là pour la suite de Trawl Watch (que ce soit pour les navires et les zones). On pourra en parler post-vacances si vous voulez, a minima pour y réfléchir ensemble.**

**Comment by marthevienne** [comment]
Pour info, je vais modifier et tester la tâche sur ma base locale. Je retiens la leçon !

**Comment by rv2931** [comment]
Ok donc y a eu un `delete from dim_zone cascade;`
Le **cascade** est proscire d'une manière générale. En fait cascade=dirty ou bien merde en cascade, c'est selon 😝

**Comment by njouanin** [comment]
Il faut encore plus proscrire le modifs sauvages en prod 🧐

**Comment by rv2931** [comment]
Oué mais on a qu'une instance commune pour le moment. Donc c'est de la test/prod 🤠

**Comment by rv2931** [comment]
Du coup le sujet reste en standby le temps de modifier le traitement ETL+vacances (ça mène à quand) ?
Pendant ce temps on pourra pas trop s'amuser avec les filtre de dates côté API
J'aurais tendance à vouloir essayer de récup les données qu'on peut récupérer d'un dump quelconque avec des données sur plusieurs mois si c'est possible. Je trouverai un moyen de les réintégrer dans la table rel_segment_zone

**Comment by marthevienne** [comment]
Je peux m'en occuper sans souci, j'ai bien compris ce qu'il fallait faire. 
Ça devrait être bon pour la fin de semaine.

**Comment by marthevienne** [comment]
Il reste juste à traiter les segments négatifs dans l'ETL. Sinon, on est bon.

**Comment by SebM42** [comment]
> Tout s'explique ! ;) S'il faut tout recalculer, attention on n'a plus toutes les données brutes dans spire_ais_data. Par contre dans vessel_positions on a tout. Donc il n'y aurait qu'à corriger le traitement `create_update_excursions_segments.py`, vider les tables fct_segment et fct_excursion, et relancer le traitement depuis le mois d'avril. Par contre ça risque d'être trèèèèèès long donc il faudra traiter par lots d'intervalles de dates je pense. @rv2931 : après réflexion, recharger les données d'une ancienne base c'est pas si évident que ça car les métriques sont fausses. pas d'autres choix que de tout recalculer à mon avis.

si le problème concerne juste la table rel_segment_zone, il suffit juste de repeupler cette table, pas besoin de recalculer les segments et excursions

**Comment by rv2931** [comment]
Je fais plusieurs vérification et à priori pas de souci à restaurer la table du dump du 30/10 dans la table de production
On aura donc un trou de relation segment/zone entre le 30/10 et le 19/11
Je viens de le faire sur la base de production. ça m'a l'air bon

**Comment by marthevienne** [comment]
Attention Hervé, je sais plus de quand date le début du dump, j'avais du sortir 3 mois.

**Comment by rv2931** [comment]
ok. ben on va faire avec ça
je pense qu'on peut clore et si jamais on trouve un autre moyen/dump de récup encore plus de relsegmentzone on fera mais le sujet est clos en lui-même je pense et sera de toutes façon résolu par un recalcule complet à venir
