### ISSUE TITLE
[DASHBOARD] - top 5 AMP visitées - filtrer que sur les AMP 

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/12_bloom#305]

**Comment by alexphiev** [comment]
Bloqué par https://github.com/dataforgoodfr/12_bloom/issues/308

**Comment by rv2931** [comment]
La #308 a été intégrée

**Comment by marthevienne** [comment]
@alexphiev, tu peux modifier ton call API pour intégrer le filtre :)
