### ISSUE TITLE
[API] Endpoint /visiting-time-by-vessel 500 Internal Server Error

### ISSUE THREAD

**Issue by alexphiev** [dataforgoodfr/12_bloom#306]
Je n'arrive plus à faire de requêtes à `/metrics/zones/660/visiting-time-by-vessel`. Ça retourne une erreur 500.

Example : 
`https://app-50bfd872-632e-4cb6-abc2-b94479db4d03.cleverapps.io/docs#/Metrics/read_metrics_zone_visiting_time_by_vessel_api_v1_metrics_zones__zone_id__visiting_time_by_vessel_get`

**Comment by marthevienne** [comment]
@rv2931 a rajouté l'argument session dans la méthode getZoneVisitingTimeByVessel. Je suppose qu'il s'agit d'une erreur.
