### ISSUE TITLE
[API] Ajouter un filtre de catégorie sur /metrics/zone-visited

### ISSUE THREAD

**Issue by alexphiev** [dataforgoodfr/12_bloom#308]
Pour récupérer le top 5 des AMPs les plus visitées, et pas de toutes les zones. 
` /api/v1/metrics/zone-visited?category=amp`

**Comment by marthevienne** [comment]
Je m'en occupe

**Comment by marthevienne** [comment]
#311 all done, attente de validation de la PR par @rv2931

**Comment by marthevienne** [comment]
En prod
