### ISSUE TITLE
[DASHBOARD] Modifier endpoint nombre de navires en mer

### ISSUE THREAD

**Issue by marthevienne** [dataforgoodfr/12_bloom#317]
@alexphiev tu as maintenant un endpoint /metrics/vessels-at-sea pour récupérer le nombre de navires qui sont partis en mer dans un temps donné :) Peux-tu me confirmer quand tu as bien pris connaissance de son existence ?

```
export function getVesselsAtSeaCount(
  startAt: string,
  endAt: string,) {
  const url = `${BASE_URL}/metrics/vessels-at-sea?start_at=${startAt}&end_at=${endAt}`
  console.log(`GET ${url}`)
  return axios.get<number>(url)
}
```

<img width="600" alt="Capture d’écran 2024-11-29 à 5 12 12 PM" src="https://github.com/user-attachments/assets/6401f7db-b62e-448b-b3ae-5804708da48e">

**Comment by alexphiev** [comment]
Déployé en prod !
