### ISSUE TITLE
[TRAJECTOIRE] Modes de visualisation des trajectoires et légende

### ISSUE THREAD

**Issue by marthevienne** [dataforgoodfr/12_bloom#353]
- [x] légende
- [x] afficher vitesse + timestamp en hover sur position (toggle Display positions ON)

Légende en bas à droite (uniquement en mode TRAJECTOIRE)
<img width="337" alt="Capture d’écran 2024-12-17 à 11 20 53 AM" src="https://github.com/user-attachments/assets/f5ea5813-df6d-40d3-aad5-2301056fd4d2" />

- Palette linéaire vitesse en mode "speed"
- type de segment : fct_segment.type = 'DEFAULT_AIS' | 'AT_SEA' | 'FISHING' (n'existe pas pour l'instant)
<img width="600" alt="Capture d’écran 2024-12-17 à 11 26 55 AM" src="https://github.com/user-attachments/assets/7bd9b9ca-1b46-4172-96e9-0c8a886e2403" />

=> Positions affichées : afficher la vitesse et timestamp en hover sur la position
<img width="312" alt="Capture d’écran 2024-12-17 à 11 44 44 AM" src="https://github.com/user-attachments/assets/af67e082-a267-4c88-bef6-4c20ba0d3419" />

**Comment by louwelgryn** [comment]
ok pour sampling -

**Comment by HenriChabert** [comment]
Je laisse tomber le sampling pour le moment!
