### ISSUE TITLE
fix checking of the excursion of the last segment

### ISSUE THREAD

**Issue by ejamet73** [dataforgoodfr/12_bloom#373]
Ligne 162 create_update_excursions_segment.py
              il y a une redondance :

                # checks if the excursion of the last segment is closed or not
                **_if vessel_last_segment["arrival_port_id"].iloc[0] and vessel_last_segment["arrival_port_id"].iloc[
                    0] >= 0_**:
                    open_ongoing_excursion = False
                else:
                    open_ongoing_excursion = True
                    ongoing_excursion_id = int(vessel_last_segment["excursion_id"].iloc[0])
                    
                    quelle est la réelle deuxième condition pour verifier que l'excursion du dernier segment est ouverte ou non ? @marthevienne

**Comment by marthevienne** [comment]
Effectivement, ça a l'air redondant. Je vérifie les valeurs.

**Comment by marthevienne** [comment]
Il faut garder la seconde condition qui suffit : vessel_last_segment["arrival_port_id"].iloc[0] >= 0
