### ISSUE TITLE
[TRAJECTOIRE] Problème couleur navire se mélangent

### ISSUE THREAD

**Issue by marthevienne** [dataforgoodfr/12_bloom#390]
Quand on ajoute un navire dans une liste déjà finie, les couleurs se mélangent
<img width="1261" alt="Capture d’écran 2024-12-19 à 2 59 22 AM" src="https://github.com/user-attachments/assets/56871f0b-80b9-4457-a74e-498008ec538e" />

**Comment by HenriChabert** [comment]
@marthevienne C'est réparé, bien vu!
