### ISSUE TITLE
Alerting : recevoir une alerte quand nous ne recevons plus de data ou quelle est malformé

### ISSUE THREAD

**Issue by RonanMorgan** [dataforgoodfr/12_bloom#4]
Pas spécialement d'idée sur ce sujet.

Est ce qu'un second script python doit également tourner toutes les heures pour faire des tests data ?  
Quel librairie peut être utilisée pour envoyer des mails ou des alertes slacks ?

Est ce qu'on part tout de suite sur une stack de monitoring dockerisé type grafana, fluentd, alertmanager ?? A terme ce sera utile mais ça fait une sacré première step

**Comment by pagbrl** [comment]
Hello ! 
Je souscris à ton analyse @RonanMorgan, je pense qu'on devrait construire la stack d'alerting en dehors de ce projet, en ayant une approche plateforme comme pour le reste (et ensuite livrer des outils type une lib python qui permet d'exposer  des metrics métier).

Pour ce cas précis un script python avec un petit check + un [webhook slack ](https://slack.dev/python-slack-sdk/webhook/index.html) feraient bien l'affaire je pense. À coordonner avec un admin du workspace slack pour obtenir le webhook et un token.

**Comment by emmanue** [comment]
Dans mon organisation on utilise Botkube pour ça.

**Comment by pagbrl** [comment]
@emmanue j'ai checké la doc de Botkube, effectivement c'est un outil intéressant.
Ceci étant dit j'ai l'impression que ça se concentre beaucoup sur les ressources Kube et moins sur du monitoring métier.

Dans l'optique qui est la notre de créer une plateforme self-service pour les devs quel que soit leur niveau, il faut qu'on garde en tête deux choses : 
- On veut des outils standardisés au maximum (bien sûr à la marge on peut adapter pour des projets qui ont des besoins particuliers). Ça donnera accès aux devs à une suite d'outils "plug-and-play", que ça soit pour le déploiement, le stockage, ou même les outils de monitoring justement
- On veut embarquer un minimum de complexité côté dev. À priori les devs n'intéragiront pas avec le(s) cluster(s) de prod, l'idée c'est qu'on opère la plateforme et les devs soient utilisateurs autonomes dessus autant que possible.

Pour ces deux raisons je pense que rajouter ce bot qui au final va les prévenir à chaque crash d'un pod mais ne va pas livrer d'info métier n'apporte pas vraiment une bonne solution. 
On aura de l'alerting sur les ressources kube bien sûr, mais on aimerait surtout que les devs poussent de l'alerting métier (comme dans ce cas où on veut une alerte si la data est plus vieille que 5 minutes, pas "juste" si le cron fail).

Dans votre cas précis, vu que ça tourne sur une VM pour le moment, et vu que la stack monitoring n'est pas encore dispo, je propose un webhook slack appelé depuis votre code python (un script qu'on peut faire tourner à interval régulier), comme ça même si on déploie sur Kube ça sera portable là-bas sans pb et avec la même config que le reste de votre app.

**Comment by emmanue** [comment]
@pagbrl  je corrobore ton analyse. Je vais faire une pr du script python en question. Merci.

**Comment by mnicolleUTC** [comment]
Salut à tous, 
Moi comme solution temporaire, je peux vous proposer Apache airflow. On fait un DAG avec un trigger déclenché sur check des datas qui tourne mal (data malformé ou interruption). On héberge ça avec un docker indépendant dans le docker compose. Ca pourrait être une solution relativement simple qui permet de répondre au besoin du jour.

**Comment by pagbrl** [comment]
Hello @mnicolleUTC, 

Pour le coup je suis pas sûr que Airflow soit vraiment une solution "simple". 
De l'impression que j'en avais un script python qui fait une query Postgres et si la data est trop vieille fait une requête http toutes les x minutes via un cron suffit donc pas sûr que ca vaille le coup qu'on héberge un airflow 😅

**Comment by mnicolleUTC** [comment]
All right, j'avoue que je lançais une idée comme ça, je me rends pas bien compte de comment sont vraiment utilisés et dans quel circonstances certains framework. Maintenant que j'y pense héberger un airflow juste pour un mail peut être pas opti. On peut faire un Zapier ? (J'essaie comme ça je me rends compte des erreurs ahaha)

**Comment by RonanMorgan** [comment]
tu as raison tkt faut balancer des idées pour en discuter :)

Zapier j'ai jamais utilisé mais j'en ai bcp entendu parler. c'est un peu la même argumentation, je pense qu'il faut vraiment commencer petit et si un jour on se retrouve avec plus de trois job ou des jobs qui dépendent les uns des autres alors on réfléchit à du tooling (airflow pour des job python, papier pour de l'intégration Slack, gmail et doc ect)

**Comment by RonanMorgan** [comment]
@SaboniAmine m'a envoyé ce lien pour qu'on s'en inspire : 
https://github.com/MTES-MCT/monitorfish/tree/master/backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/alert

**Comment by shadzic** [comment]
Hello
Si vous utilisez Airflow, il est très simple d'ajouter une alerte slack au DAG: https://towardsdatascience.com/automated-alerts-for-airflow-with-slack-5c6ec766a823
