### ISSUE TITLE
Ajouter les zones géographiques dans la base PostGre des zones

### ISSUE THREAD

**Issue by TheoLvs** [dataforgoodfr/12_bloom#48]
- Continents 
- Pays
- Zone économique exclusive

Si on trouve des fichiers géographiques de polygones, c'est quoi la meilleure méthode pour les intégrer dans la base @RonanMorgan  @SaboniAmine  ?

**Comment by SaboniAmine** [comment]
Si tu as une fonction qui permet de déduire ces colonnes, le plus simple est de faire un fichier de migration alembic + un script d'alimentation (transformation) de ces colonnes. 
Pour le pays on a les colonnes PARENT_ISO & ISO3 qui permettent d'identifier le pays (il y a 3 zones qui appartiennent à plusieurs pays), il ne manquerait que la conversion pays -> ZEE à implémenter.

**Comment by RonanMorgan** [comment]
je veux bien essayer de faire ça ce soir si c'est prio @TheoLvs
