### ISSUE TITLE
Good pratice python launched with precommit hook

### ISSUE THREAD

**Issue by RonanMorgan** [dataforgoodfr/12_bloom#7]
=> ajouter un precommit hook pour le linting du code python (j'ai des exemples au boulot si besoin :)
=> lancer également un test unitaire (juste une première step)

**Comment by n-toussaint** [comment]
ça pourrait être utile d'avoir mypy (ou équivalent) pour vérifier la cohérence des type hints. 
J'en ai vu quelques-uns donc on pourrait capitaliser la dessus !

**Comment by Erawpalassalg** [comment]
Pour le moment les hints sont utilisés seulement pour pydantic, il me semble.

En soi, je suis assez d'accord, et pas de souci pour m'en occuper mais peut-être dans le cadre d'une autre PR ?

**Comment by n-toussaint** [comment]
oui, tu as raison :)
